default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    cocoapods(podfile: "Podfile", use_bundle_exec: false)
    build_number = increment_build_number
    Dir.chdir ".." do
      sh("flutter", "clean")
      sh("flutter", "pub", "get")
      sh("flutter", "build", "ios", "--release", "--no-codesign", "--build-number=#{build_number}")
    end
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_xcargs: "-allowProvisioningUpdates")
    changelog_from_git_commits()
    upload_to_testflight(
      reject_build_waiting_for_review: true,
    )
    upload_symbols_to_crashlytics(dsym_path: "./Runner.app.dSYM.zip")
    notification(subtitle: "Success", message: "App pushed to TestFlight")
  end
end
